### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by advaitraut** [ExaScience/bpmf#1]
On Mac OS (v10.10 ), it require to install library _GASPI (gpi2)_ which is further dependent on _libibverbs_.
I am not able to install libibverbs on mac. Some inputs on this would be appreciated.

**Comment by tvandera** [comment]
GASPI/GPI2 support only makes sense on a cluster (with infiniband). On you MAC, you should use one of the nocomm- versions.

**Comment by advaitraut** [comment]
Thanks @tvandera 
I am trying installation from _nocomm-omp_ directory.
During the _make_ the program compiles and generates executable but gives linking warnings on Mac.

`g++-6 -fopenmp -DBPMF_NO_COMM  -DBPMF_OMP_SCHED -DBPMF_PROFILING -std=c++11 -Wall -Wextra -Wfatal-errors -I../.. -I/usr/local/include/eigen3 -O3 -ffast-math -g -fstrict-aliasing -DNDEBUG -march=native -flto   bpmf.o mvnormal.o sample.o counters.o   -o bpmf`

I am pasting few lines out of many from linking warnings:

```
warning: (x86_64)  could not find object file symbol for symbol __ZN3Sys6sampleElN5Eigen3MapINS0_6MatrixIdLi100ELin1ELi0ELi100ELin1EEELi0ENS0_6StrideILi0ELi0EEEEE
warning: (x86_64)  could not find object file symbol for symbol __ZN3Sys4initERKS_
warning: (x86_64)  could not find object file symbol for symbol __Z19read_sparse_float64RN5Eigen12SparseMatrixIdLi0EiEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

and then execution output:
```
$ ./bpmf
Usage: ./bpmf [-t <threads>] [-i <iterations>] -n <samples.mtx> -p <probe.mtx>
Abort trap: 6
```

Is that the expected behaviour ?

**Comment by tvandera** [comment]
Yes, these warnings are normal on Mac with GCC.

Have a look at the EuroMPI16 branch for beter instructions on running BPMF.

Tom

**Comment by advaitraut** [comment]
@tvandera Thanks. 
I built it with EuroMPI16 branch and it gave no warnings. the binary is also executed without any problem.
