### ISSUE TITLE
How do you compute the actual ratings?

### ISSUE THREAD

**Issue by Modestas96** [ExaScience/bpmf#2]
Hi, the script outputs 4 vectors, but how do you actually compute the predictions with them?

**Comment by tvandera** [comment]
Hello Modestas, What script are you talking about? T.

**Comment by Modestas96** [comment]
Hi, sorry for not giving you enough details:
bpmf -n <MTX> -p <MTX> [-o DIR/]
I'm running bpmf script, which outputs:

U-Lambda.ddm
U-mu.ddm
V-Lambda.ddm
V-mu.ddm

and 
Pavg.sdm
Pm2.sdm

Is there any additional commands (options) that I can run in order to get the predicted ratings on the test set?

**Comment by tvandera** [comment]
Good, thanks for the deatils. I think you're better off using SMURFF, which has a nice python interface. https://github.com/ExaScience/smurff
and good documentation: https://smurff.readthedocs.io/

**Comment by Modestas96** [comment]
Thank you!
