### ISSUE TITLE
advise

### ISSUE THREAD

**Issue by limits220284** [ExaScience/bpmf#7]
Dear author,I want to repeat the project myself,How long do you think it will take for one person ? I am a undergraduate student with a common programming ability。Thank you!

**Comment by tvandera** [comment]
Do you want to rewrite the complete C++ code? Including the MPI, GASPI, OpenMP, ... ? That would take several months/years.


There is simple [Julia](https://github.com/ExaScience/bpmf/blob/master/julia/bpmf.jl) and [Matlab](https://github.com/ExaScience/bpmf/blob/master/bayespmf.m) code to start from.

**Comment by limits220284** [comment]
> Do you want to rewrite the complete C++ code? Including the MPI, GASPI, OpenMP, ... ? That would take several months/years.
> 
> There is simple [Julia](https://github.com/ExaScience/bpmf/blob/master/julia/bpmf.jl) and [Matlab](https://github.com/ExaScience/bpmf/blob/master/bayespmf.m) code to start from.

Thank you for your reply!, I have read the paper[Distributed Matrix Factorization using Asynchrounous Communication](https://arxiv.org/pdf/1705.10633.pdf).  Currently, I just want to implement the third part(Multi-core-based parallel BPMF), not considering the part four(Distributed parallel BPMF). I'm not sure if this work can be completed in the short term. Thank you for your suggestion！

**Comment by limits220284** [comment]
> Do you want to rewrite the complete C++ code? Including the MPI, GASPI, OpenMP, ... ? That would take several months/years.
> 
> There is simple [Julia](https://github.com/ExaScience/bpmf/blob/master/julia/bpmf.jl) and [Matlab](https://github.com/ExaScience/bpmf/blob/master/bayespmf.m) code to start from.

emmm,another question, if I only want to implement the  third part(Multi-core-based parallel BPMF) using the OpenMP, How long do you think it will take for me ? Thank you!

**Comment by tvandera** [comment]
I would say this is a semester project.
